-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.airport
(
    airport_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    airline_code character varying(10) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    country character varying(100) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updete_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT airport_pkey PRIMARY KEY (airport_id),
    CONSTRAINT airport_airline_code_key UNIQUE (airline_code)
);

CREATE TABLE IF NOT EXISTS public.flight
(
    flight_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    departing_gate character varying(100) COLLATE pg_catalog."default",
    arriving_gate character varying(100) COLLATE pg_catalog."default",
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    airline_id integer NOT NULL,
    deporture_airport_id integer NOT NULL,
    arrival_airport_id integer NOT NULL,
    schaduled_deporture_time timestamp without time zone NOT NULL,
    schadule_arrival_time timestamp without time zone NOT NULL,
    actual_deporture_time timestamp without time zone NOT NULL,
    actual_arrival_time timestamp without time zone NOT NULL,
    CONSTRAINT flight_pkey PRIMARY KEY (flight_id)
);

CREATE TABLE IF NOT EXISTS public.booking
(
    booking_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    flight_id integer NOT NULL,
    passenger_id integer NOT NULL,
    status character varying(30) COLLATE pg_catalog."default" NOT NULL,
    booking_platform character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ticket_price numeric(10, 2) NOT NULL,
    CONSTRAINT booking_pkey PRIMARY KEY (booking_id)
);

CREATE TABLE IF NOT EXISTS public.passenger
(
    passenger_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    gender character varying(20) COLLATE pg_catalog."default",
    date_of_birth date NOT NULL,
    country_of_citizenship character varying(100) COLLATE pg_catalog."default" NOT NULL,
    country_of_residence character varying(100) COLLATE pg_catalog."default" NOT NULL,
    passport_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT passenger_pkey PRIMARY KEY (passenger_id),
    CONSTRAINT passenger_passport_number_key UNIQUE (passport_number)
);

CREATE TABLE IF NOT EXISTS public.baggage_check
(
    baggage_check_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    check_result character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    booking_id integer NOT NULL,
    passenger_id integer NOT NULL,
    CONSTRAINT baggage_check_pkey PRIMARY KEY (baggage_check_id)
);

CREATE TABLE IF NOT EXISTS public.security_check
(
    security_check_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    check_result character varying(50) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    passenger_id integer NOT NULL,
    CONSTRAINT security_check_pkey PRIMARY KEY (security_check_id)
);

CREATE TABLE IF NOT EXISTS public.boarding_pass
(
    boarding_pass_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    seat character varying(10) COLLATE pg_catalog."default" NOT NULL,
    boarding_time timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    booking_id integer NOT NULL,
    CONSTRAINT boarding_pass_pkey PRIMARY KEY (boarding_pass_id),
    CONSTRAINT boarding_pass_booking_id_key UNIQUE (booking_id)
);

CREATE TABLE IF NOT EXISTS public.baggage
(
    baggage_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    weight_kg numeric(5, 2) NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    booking_id integer NOT NULL,
    CONSTRAINT baggage_pkey PRIMARY KEY (baggage_id)
);

ALTER TABLE IF EXISTS public.flight
    ADD CONSTRAINT fk_fligh_arrival_airport FOREIGN KEY (arrival_airport_id)
    REFERENCES public.airport (airport_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.flight
    ADD CONSTRAINT fk_flight_airline FOREIGN KEY (airline_id)
    REFERENCES public.airport (airport_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.flight
    ADD CONSTRAINT fk_flight_deporture_airport FOREIGN KEY (deporture_airport_id)
    REFERENCES public.airport (airport_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT fk_booking_flight FOREIGN KEY (flight_id)
    REFERENCES public.flight (flight_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.booking
    ADD CONSTRAINT fk_booking_passenger FOREIGN KEY (passenger_id)
    REFERENCES public.passenger (passenger_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.baggage_check
    ADD CONSTRAINT fk_baggage_check_booking FOREIGN KEY (booking_id)
    REFERENCES public.booking (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.baggage_check
    ADD CONSTRAINT fk_baggage_check_passenger FOREIGN KEY (passenger_id)
    REFERENCES public.passenger (passenger_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.security_check
    ADD CONSTRAINT fk_security_check_passenger FOREIGN KEY (passenger_id)
    REFERENCES public.passenger (passenger_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.boarding_pass
    ADD CONSTRAINT fk_boarding_pass_booking FOREIGN KEY (booking_id)
    REFERENCES public.booking (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS boarding_pass_booking_id_key
    ON public.boarding_pass(booking_id);


ALTER TABLE IF EXISTS public.baggage
    ADD CONSTRAINT fk_baggage_booking FOREIGN KEY (booking_id)
    REFERENCES public.booking (booking_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;